var productArray = [{
        productID: 101,
        img: './img/products/sanpham1.jpg',
        img1: './img/products/ChiTietSanPham/ssultra1.jpg',
        img2: './img/products/ChiTietSanPham/ssultra2.jpg',
        img3: './img/products/ChiTietSanPham/ssultra3.jpg',
        img4: './img/products/ChiTietSanPham/ssultra4.jpg',
        img5: './img/products/ChiTietSanPham/ssultra5.jpg',
        name: 'Samsung Galaxy S22 Ultra 5G',
        oldPrice: 31990000,
        newPrice: 30990000,
        description: 'Galaxy S22 Ultra 5G chiếc smartphone cao cấp nhất trong bộ 3 Galaxy S22 series mà Samsung đã cho ra mắt. Tích hợp bút S Pen hoàn hảo trong thân máy, trang bị vi xử lý mạnh mẽ cho các tác vụ sử dụng vô cùng mượt mà và nổi bật hơn với cụm camera không viền độc đáo mang đậm dấu ấn riêng.',
        detailDescription: 'Sở hữu một diện mạo đầy nổi bật Galaxy S22 Ultra 5G được kế thừa form thiết kế từ những dòng Note trước đây của hãng đem đến cho bạn có cảm giác vừa mới lạ vừa hoài niệm. Trọng lượng của máy khoảng 228 g cho cảm giác cầm nắm đầm tay, khi cầm máy trần thì hơi có cảm giác dễ trượt',
    },
    {
        productID: 102,
        img: './img/products/sanpham2.jpg',
        img1: './img/products/ChiTietSanPham/ssgalaxya1.jpg',
        img2: './img/products/ChiTietSanPham/ssgalaxya2.jpg',
        img3: './img/products/ChiTietSanPham/ssgalaxya3.jpg',
        img4: './img/products/ChiTietSanPham/ssgalaxya4.jpg',
        img5: './img/products/ChiTietSanPham/ssgalaxya5.jpg',
        name: 'Samsung Galaxy A03',
        oldPrice: 2990000,
        newPrice: 2890000,
        description: 'Samsung Galaxy A03 là chiếc điện thoại Galaxy A đầu tiên của nhà Samsung trong năm 2022 tại thị trường Việt Nam. Đây là sản phẩm có mức giá dễ tiếp cận, có camera chính đến 48 MP, pin 5000 mAh thoải mái sử dụng cả ngày.',
        detailDescription: 'Galaxy A03 có thiết kế nhựa nguyên khối, mặt lưng nhám, có các đường vân đan chéo nhau một cách nhẹ nhàng mang lại độ nhám nhất định khi cầm nắm, cảm giác đầm tay và có thể hạn chế bám mồ hôi, dấu vân tay. Phần khung viền được vát cong, ôm về phía trước nên cho cảm giác máy mỏng hơn, tạo cho mình cảm giác cầm nắm rất là thoải mái cộng thêm với việc đặt vị trí phím tăng giảm âm lượng, phím nguồn hợp lý thì khi cầm sản phẩm một thời gian dài mình không gặp một bất tiện nào.',
    }, {
        productID: 103,
        img: './img/products/sanpham3.jpg',
        name: 'Samsung Galaxy A52s 5G 128GB',
        img1: './img/products/ChiTietSanPham/ssa52s1.jpg',
        img2: './img/products/ChiTietSanPham/ssa52s2.jpg',
        img3: './img/products/ChiTietSanPham/ssa52s3.jpg',
        img4: './img/products/ChiTietSanPham/ssa52s4.jpg',
        img5: './img/products/ChiTietSanPham/ssa52s5.jpg',
        oldPrice: 10990000,
        newPrice: 8990000,
        description: 'Galaxy S22 Ultra 5G chiếc smartphone cao cấp nhất trong bộ 3 Galaxy S22 series mà Samsung đã cho ra mắt. Tích hợp bút S Pen hoàn hảo trong thân máy, trang bị vi xử lý mạnh mẽ cho các tác vụ sử dụng vô cùng mượt mà và nổi bật hơn với cụm camera không viền độc đáo mang đậm dấu ấn riêng.',
        detailDescription: 'Sở hữu một diện mạo đầy nổi bật Galaxy S22 Ultra 5G được kế thừa form thiết kế từ những dòng Note trước đây của hãng đem đến cho bạn có cảm giác vừa mới lạ vừa hoài niệm. Trọng lượng của máy khoảng 228 g cho cảm giác cầm nắm đầm tay, khi cầm máy trần thì hơi có cảm giác dễ trượt',
    }, {
        productID: 104,
        img: './img/products/sanpham4.jpg',
        img1: './img/products/ChiTietSanPham/xiaomi11t1.jpg',
        img2: './img/products/ChiTietSanPham/xiaomi11t2.jpg',
        img3: './img/products/ChiTietSanPham/xiaomi11t3.jpg',
        img4: './img/products/ChiTietSanPham/xiaomi11t4.jpg',
        img5: './img/products/ChiTietSanPham/xiaomi11t5.jpg',
        name: 'Xiaomi 11T',
        oldPrice: 10990000,
        newPrice: 9490000,
        description: 'Xiaomi 11T đầy nổi bật với thiết kế vô cùng trẻ trung, màn hình AMOLED, bộ 3 camera sắc nét và viên pin lớn đây sẽ là mẫu smartphone của Xiaomi thỏa mãn mọi nhu cầu giải trí, làm việc và là niềm đam mê sáng tạo của bạn.',
        detailDescription: 'Xiaomi trang bị cho 11T 3 camera sau gồm camera chính độ phân giải 108 MP, camera góc rộng 8 MP 120 độ và camera telemacro 5 MP cùng hệ thống phần cứng tối tân được trang bị bên trong cực kỳ ấn tượng. Chỉ cần giơ máy lên chụp là bạn đã có những bức ảnh sắc nét đáng kinh ngạc, khả năng thu phóng cũng cực tốt, cho bạn chụp được rõ từng chi tiết dù đối tượng ở khá xa. Chụp phong cảnh, ảnh nhóm dễ dàng nhờ camera góc rộng 120 độ. Chụp ảnh với camera telemacro giúp bạn khám phá một thế giới thu nhỏ đầy thú vị, với tiêu điểm khoảng 3 - 7 cm dễ dàng quan sát được các vật thể nhỏ như giọt sương trên ngọn cỏ, cánh bướm,... ',
    }, {
        productID: 105,
        img: './img/products/sanpham5.jpg',
        img1: './img/products/ChiTietSanPham/redminote10pro1.jpg',
        img2: './img/products/ChiTietSanPham/redminote10pro2.jpg',
        img3: './img/products/ChiTietSanPham/redminote10pro3.jpg',
        img4: './img/products/ChiTietSanPham/redminote10pro4.jpg',
        img5: './img/products/ChiTietSanPham/redminote10pro5.jpg',
        name: 'Xiaomi Redmi Note 10 Pro (8GB/128GB)',
        oldPrice: 8990000,
        newPrice: 7490000,
        description: 'Kế thừa và nâng cấp từ thế hệ trước, Xiaomi đã cho ra mắt Xiaomi Redmi Note 10 Pro (8GB/128GB) sở hữu một thiết kế cao cấp, sang trọng bên cạnh cấu hình vô cùng mạnh mẽ, hứa hẹn mang đến sự cạnh tranh lớn trong phân khúc smartphone tầm trung.',
        detailDescription: 'Xiaomi Redmi Note 10 Pro có thiết kế nguyên khối mang lại cảm giác rất đầm tay và chắc chắn, bên cạnh việc trang bị mặt kính ở hai cả hai mặt, tăng khả năng chống chịu va đập và các trầy xước không mong muốn.Thiết kế sang trọng với khung viền được gia công bằng vật liệu kim loại cao cấp, máy sử dụng bản màu thanh lịch với những màu sắc trẻ trung và năng động tùy chọn theo sở thích.',
    }, {
        productID: 106,
        img: './img/products/sanpham6.jpg',
        img1: './img/products/ChiTietSanPham/redmi9a1.jpg',
        img2: './img/products/ChiTietSanPham/redmi9a2.jpg',
        img3: './img/products/ChiTietSanPham/redmi9a3.jpg',
        img4: './img/products/ChiTietSanPham/redmi9a4.jpg',
        img5: './img/products/ChiTietSanPham/redmi9a5.jpg',
        name: 'Xiaomi Redmi 9A',
        oldPrice: 2490000,
        newPrice: 2390000,
        description: 'Redmi 9A là chiếc smartphone đến từ Xiaomi hướng tới nhóm khách hàng đang tìm kiếm cho mình một sản phẩm với cấu hình tốt giá thành phải chăng, cũng như được trang bị đầy đủ các tính năng ấn tượng.',
        detailDescription: 'Giống như người anh Redmi 9 của mình, Xiaomi Redmi 9A được trang bị màn hình giọt nước tràn viền kích thước lớn 6.53 inch tỉ lệ 20:9 cho khả năng hiển thị được nhiều thông tin mà vẫn nhỏ gọn trong bàn tay người dùng. Tuy màn hình của máy chỉ cho độ phân giải HD+ nhưng vẫn đảm bảo được chất lượng hiển thị sắc nét, cho bạn thoải mái sử dụng các tác vụ như đọc báo xem phim lướt web hằng ngày.',
    }, {
        productID: 107,
        img: './img/products/sanpham7.jpg',
        img1: './img/products/ChiTietSanPham/iphone13promax1.jpg',
        img2: './img/products/ChiTietSanPham/iphone13promax2.jpg',
        img3: './img/products/ChiTietSanPham/iphone13promax3.jpg',
        img4: './img/products/ChiTietSanPham/iphone13promax4.jpg',
        img5: './img/products/ChiTietSanPham/iphone13promax5.jpg',
        name: 'iPhone 13 Pro Max',
        oldPrice: 36990000,
        newPrice: 34290000,
        description: 'iPhone 13 Pro Max 256 GB - siêu phẩm mang trên mình bộ vi xử lý Apple A15 Bionic hàng đầu, màn hình Super Retina XDR 120 Hz, cụm camera khẩu độ f/1.5 cực lớn, tất cả sẽ mang lại cho bạn những trải nghiệm tuyệt vời chưa từng có.',
        detailDescription: 'iPhone 13 Pro Max vẫn sẽ kế thừa thiết kế đặc trưng của iPhone 12 Series, vẫn là một sản phẩm với khung viền được hoàn thiện từ thép không gỉ, hai mặt trước sau được trang bị kính cường lực bóng bẩy. Điểm thay đổi lớn trên 13 Pro Max có thể là phần module camera được làm to hơn khá nhiều, phần cạnh viền máy được vát phẳng sang trọng cùng bốn góc được làm bo cong nhẹ, phủ một lớp mờ giúp hạn chế bám bụi bẩn và vân tay',
    }, {
        productID: 108,
        img: './img/products/sanpham8.jpg',
        img1: './img/products/ChiTietSanPham/iphone12promax1.jpg',
        img2: './img/products/ChiTietSanPham/iphone12promax2.jpg',
        img3: './img/products/ChiTietSanPham/iphone12promax3.jpg',
        img4: './img/products/ChiTietSanPham/iphone12promax4.jpg',
        img5: './img/products/ChiTietSanPham/iphone12promax5.jpg',
        name: 'iPhone 12 Pro Max',
        oldPrice: 31990000,
        newPrice: 28990000,
        description: 'Chiếc điện thoại iPhone 12 Pro Max 256 GB là mẫu smartphone sở hữu nhiều tính năng nổi bật với hệ thống camera chất lượng, hiệu năng vượt trội hay hỗ trợ kết nối 5G hứa hẹn sẽ là mẫu sản phẩm mang lại cảm giác trải nghiệm tối ưu cho người dùng.',
        detailDescription: 'Một sự cải tiến được coi là nguồn lõi và là trái tim hay nguồn sức mạnh để có thể vận hành một chiếc điện thoại siêu phẩm 2020 đó là chipset A14 Bionic được sản xuất trên tiến trình 5 nm cho phép tạo ra 11.8 tỷ bóng bán dẫn mang đến hiệu năng vô cùng mạnh mẽ. iOS 15 (12/2021) cũng được cài sẵn trên máy và mang nhiều điểm cải tiến giúp máy được tối ưu tốt hơn nâng cao hiệu năng.',
    }, {
        productID: 109,
        img: './img/products/sanpham9.jpg',
        img1: './img/products/ChiTietSanPham/iphone13mini1.jpg',
        img2: './img/products/ChiTietSanPham/iphone13mini2.jpg',
        img3: './img/products/ChiTietSanPham/iphone13mini3.jpg',
        img4: './img/products/ChiTietSanPham/iphone13mini4.jpg',
        img5: './img/products/ChiTietSanPham/iphone13mini5.jpg',
        name: 'iPhone 13 mini',
        oldPrice: 21990000,
        newPrice: 19990000,
        description: 'iPhone 13 mini được Apple ra mắt với hàng loạt nâng cấp về cấu hình và các tính năng hữu ích, lại có thiết kế vừa vặn. Chiếc điện thoại này hứa hẹn là một thiết bị hoàn hảo hướng tới những khách hàng thích sự nhỏ gọn nhưng vẫn giữ được sự mạnh mẽ bên trong. ',
        detailDescription: 'iPhone 13 mini được trang bị bộ vi xử lý A15 Bionic sản xuất trên tiến trình 5 nm giúp cải thiện hiệu suất và giảm điện năng tiêu thụ đến 15% so với phiên bản A14 Bionic trước đó, đáp ứng hoàn hảo trong công việc cũng như trong giải trí của người dùng tốt hơn. CPU 6 lõi cho hiệu suất hoạt động tăng 40% cùng với đó là GPU cũng có mức hiệu năng tăng mạnh lên đến 80% so với chipset thế hệ trước. Bạn hoàn toàn có thể chơi game mượt mà, các thao tác chỉnh sửa hình ảnh, cắt ghép video đều vô cùng trơn tru.',
    },
];


var formatter = new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND',
});

function getProductIndex(productid) {
    return productArray.findIndex(e => e.productID == productid);
}